// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CallMethod(arg1, arg2) {
  return window['go']['client']['APIBridge']['CallMethod'](arg1, arg2);
}
