server {
        listen 80;
        server_name install.tunnels.is;
        location = / {
                root /var/www/server;
                try_files /install.sh =404;
                default_type application/x-sh;
                add_header Content-Disposition "attachment; filename=install.sh" always;
        }
}
